In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)


arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)


arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr3)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#Array of zero
zero_arr = np.zeros((2,3))
print("Array of Zero :\n",zero_arr)

#Array of 1
one_arr = np.ones((2,4))
print("Array of Ones :\n",one_arr)

#Filled with const values
filled_arr = np.full((3,5),6)
print("Array of Filled :\n",filled_arr)

#Indentity matrix
identity_arr = np.eye(5)
print("Identity Matrix :\n",identity_arr)

Array of Zero :
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of Filled :
 [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
Identity Matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
range_arr = np.arange(1,10,2)
print("Range_arr : \n",range_arr)

lin_arr = np.linspace(0,1,5)
print("Line space :\n",lin_arr)

rand_arr = np.random.rand(2,6)
print(rand_arr)

randint_arr = np.random.randint(1, 100, size=(2, 3)) 
print(randint_arr)

Range_arr : 
 [1 3 5 7 9]
Line space :
 [0.   0.25 0.5  0.75 1.  ]
[[0.13674494 0.90885441 0.1281756  0.58052776 0.00493378 0.50660816]
 [0.64099733 0.51529089 0.94492702 0.70602976 0.98884163 0.61531958]]
[[73 69 25]
 [84 43 48]]


In [62]:
ex1 = np.zeros((4,4))
print(ex1,"\n")
ex2 = np.arange(10,51,5)
print(ex2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[10 15 20 25 30 35 40 45 50]


In [72]:
sample = np.array(((1,2,3),(4,5,6)))
print(sample.shape)
print(sample.ndim)
print(sample.size)
print(sample.dtype)


(2, 3)
2
6
int64


In [78]:
reshaped = sample.reshape(3,2)
print(reshaped)

flat = sample.flatten()
print( flat)

print( sample.T)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [81]:
a = np.array((1,2,3))
b= np.array((4,5,6))
join = np.concatenate((a,b))
print(join)

print(np.vstack((a,b)))
print(np.hstack((a,b)))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [83]:
unsorted = np.array((1,2,9,65,4,3,4))
print(np.sort(unsorted))

[ 1  2  3  4  4  9 65]


In [87]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print( ex2.shape)
print( ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

(2, 3)
6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
x = np.array((1,2,3,5,3,7,8))
y = np.array((3,5,8,4,8,5,3))

print("Sum :",np.sum(x))
print("Mean :",np.mean(x))
print("MIN :",np.min(x))
print("MAX :",np.max(x))
print("VAR :",np.var(x))
print("SD :",np.std(x))


Sum : 29
Sum : 4.142857142857143
Sum : 1
Sum : 8
Sum : 5.836734693877552
Sum : 2.415933503612538


In [97]:
print("sq root :" ,np.sqrt(x))
print("Exponential:" ,np.exp(x))
print("Log :" ,np.log(x))
print("Sine", np.sin(x))

sq root : [1.         1.41421356 1.73205081 2.23606798 1.73205081 2.64575131
 2.82842712]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 1.48413159e+02
 2.00855369e+01 1.09663316e+03 2.98095799e+03]
Log : [0.         0.69314718 1.09861229 1.60943791 1.09861229 1.94591015
 2.07944154]
Sine [ 0.84147098  0.90929743  0.14112001 -0.95892427  0.14112001  0.6569866
  0.98935825]


In [101]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print( m1*m2)

print(np.dot(m1,m2))

print(np.matmul(m1,m2))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [103]:
p = np.array([2, 4, 6, 8, 10])
q = np.array([1, 3, 5, 7, 9])

print(p+q)
print(p*q)
print(np.mean(p+q))

[ 3  7 11 15 19]
[ 2 12 30 56 90]
11.0


In [111]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::2])
print(arr[::-1])

[10 20 30 40 50 60]
10
60
[20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
